"""The drawing list: one plate per shot in DIRECTION.md. Writes prompts/<name>.txt.

Style is shared (prompts/_style.txt). Colour is rationed on purpose: graphite for the night,
cyanotype blueprint for the machine, one lavender glint for Looper, watercolour only at dawn.
"""
from pathlib import Path

PLATES = {
    "eye-night": "SUBJECT: extreme close-up of ONE eye of the developer behind a round wire-rim glasses lens, at night. The lens reflects a bright monitor as a curved white rectangle with faint horizontal lines like rows of code, and one tiny bright SQUARE in it. Tired eye, slight dark circle beneath, a few strands of hair. The face is lit only by the cold monitor glow from the front; everything else falls to deep graphite black.",
    "eye-dawn": "SUBJECT: the same extreme close-up of ONE eye of the developer behind a round wire-rim glasses lens, but at sunrise: the lens reflects a steel window grid of square panes with a round rising SUN inside it. The eye is rested and calm. Graphite pencil with soft WATERCOLOR washes: warm amber and peach light on the skin and in the reflection; the rest stays graphite.",
    "monitor-cu": "SUBJECT: close-up of a wide computer monitor seen straight on, slightly from below, in a dark room. The screen is completely BLANK glowing paper-white (leave the screen empty, pure white, no content at all). Around it: the dark bezel, a small sticky note on the lower-left corner of the bezel, the edge of a coffee mug, the monitor's light spilling onto the desk. Symmetric, graphic composition.",
    "note-clock": "SUBJECT: close-up still life at night: a square pale sticky note stuck on the edge of a dark monitor bezel (the note is BLANK, no writing), and above it, on the concrete wall, a small rectangular digital wall clock whose display is BLANK and glowing. The note sharp in the foreground, the clock softer behind.",
    "rub-eyes": "SUBJECT: medium side-profile shot of the developer at the desk, leaning back in the office chair, glasses pushed up onto the forehead, rubbing their closed eyes hard with the heels of both hands: exhausted. The monitor glow rim-lights their profile from the left. Dark room behind.",
    "hands-keyboard": "SUBJECT: close-up of two hands over a computer keyboard at night, seen from slightly above and in front: one index finger about to press a single key; the fingers hesitate, tense. Monitor glow from above lights the knuckles; the keys fall into darkness.",
    "phone-desk": "SUBJECT: top-down close-up of a smartphone lying face-up on a dark wooden desk at night; the phone screen glows BLANK white (no content) and lights the wood grain and a few crumbs of eraser around it. A hand's fingertips entering from the edge, about to tap it.",
    "neighbour-window": "SUBJECT: seen from across a dark street with a long lens: the facade of an apartment building at night, a grid of dark SQUARE windows; exactly one window is lit, and inside it a small silhouette of another person hunched at a desk in front of a glowing screen. Rain in the air. Loneliness, shared.",
    "asleep-desk": "SUBJECT: the developer asleep at the desk, head down on folded arms beside the keyboard, glasses askew, hood half up; seen from a low angle at desk level. The monitor above still glows blank white and lights the top of their hair. A cold coffee mug. Deep night.",
    "machine-track": "SUBJECT: a TECHNICAL DRAWING in the style of an architect's CYANOTYPE BLUEPRINT (Prussian blue paper, crisp white ink lines, ruler-straight): a single straight rail track in one-point perspective racing toward the horizon through rows of tall square pillars; far down the track stands one square GATE frame across the rail. Construction lines, dimension lines and hatching, drafting-compass marks. Only white lines on deep blue, no other colours.",
    "machine-plan": "SUBJECT: a TOP-DOWN PLAN VIEW technical drawing in the style of a CYANOTYPE BLUEPRINT (Prussian blue paper, crisp white ink lines): four parallel straight rail tracks crossing the sheet, each blocked again and again by SQUARE gate symbols, surrounded by a dense grid of small square pillars; the whole sheet reads like a maze or a cage made of squares. Drafting marks and hatching; an empty circular space left in the centre. Only white lines on deep blue.",
    "orb": "SUBJECT: close-up still life: a small perfect GLASS SPHERE sitting on the dark desk at night, with a smooth folded ribbon of glass inside it like a sculpted S-curve. The sphere refracts and reflects four tiny bright SQUARES (distant monitor panes). Extremely careful rendering of glass highlights with the eraser, EXCEPT one single faint LAVENDER glint inside the sphere, the only colour in the image.",
    "wake-phone": "SUBJECT: close-up of the developer's face jolting awake at the desk, cheek still pressed against the forearm, one eye open, lit from below by the cold glow of a phone screen close by; hair messy, glasses crooked. Shock and dread. Deep darkness around.",
    "ots-monitor": "SUBJECT: over-the-shoulder shot from behind the developer's head and shoulder (dark silhouette in the foreground) looking at a wide monitor divided into FOUR blank glowing rectangular panes (a 2 by 2 grid, all panes empty white). A small digital clock on the wall above (blank display) and a sticky note on the bezel. Night.",
    "look-orb": "SUBJECT: medium shot of the developer seated at the desk at night, head turned, looking down at a small glass sphere on the desk next to the keyboard; the sphere glows with a soft LAVENDER light that falls on their face and glasses, the only colour in the drawing. Their expression: a decision forming. Monitor glow from the other side.",
    "stand-up": "SUBJECT: low-angle dynamic shot: the developer rising out of the office chair in one motion, the chair rolling back and spinning away behind them with pencil motion lines; backlit by the monitor which now glows LAVENDER, lavender light spilling across the floor, the only colour. Energy, release.",
    "walk-window": "SUBJECT: wide shot: the developer walking away from the desk across the concrete loft, passing in front of the huge steel window grid of square panes, silhouetted against the city lights; behind them the empty desk, the monitor and a small sphere glowing LAVENDER, the only colour. Relief in their posture.",
    "couch-phone": "SUBJECT: close shot from above: the developer lying on their back on a couch, relaxed, holding a phone above their face with one hand, reading; the phone screen is BLANK glowing white and lights their face; a slight smile. A blanket. Night.",
    "couch-sleep-wide": "SUBJECT: wide shot of the loft at night from the far side: the developer asleep on the couch under the big square-paned window; far across the room the empty desk with the monitor and the glass sphere glowing soft LAVENDER, the only colour; the office chair turned away, empty. Peace.",
    "dawn-wide": "SUBJECT: the same loft at SUNRISE, graphite pencil with loose WATERCOLOR washes: warm amber and rose light pours through the steel window grid of square panes, a big round sun inside the grid, long square shadows stretching across the floor toward the empty desk; the developer still asleep on the couch under the window. Colour arrives for the first time: amber, peach, and a touch of lavender on the glass sphere.",
    "stretch": "SUBJECT: the developer sitting up on the couch at sunrise, arms stretched high over their head, yawning, rested, in warm side light from the window. Graphite pencil with loose WATERCOLOR washes of amber and peach.",
    "window-silhouette": "SUBJECT: the developer standing at the big steel window grid at sunrise, seen from behind, a phone in one hand at their side, looking out at the city and the round rising sun framed inside one square pane. Graphite pencil with loose WATERCOLOR washes of amber, rose and pale gold.",
}

for name, text in PLATES.items():
    (Path(__file__).parent / "prompts" / f"{name}.txt").write_text(text + "\n")
print(" ".join(PLATES))
