/* Generated by tools/make-narration.mjs — do not edit by hand. */
window.LEGEND_NARRATION = [
  {
    "id": "legend",
    "speaker": "narrator",
    "text": "Legend tells of a king who sailed for ten years…",
    "start": 10.6,
    "duration": 4.056,
    "file": "narration/legend.mp3"
  },
  {
    "id": "untouched",
    "speaker": "narrator",
    "text": "…and never once touched his work.",
    "start": 15.156,
    "duration": 2.904,
    "file": "narration/untouched.mp3"
  },
  {
    "id": "desk",
    "speaker": "narrator",
    "text": "He left it at home, on a desk beneath an olive tree,",
    "start": 19.66,
    "duration": 4.2,
    "file": "narration/desk.mp3"
  },
  {
    "id": "thread",
    "speaker": "narrator",
    "text": "and tied it to his hand with a single red thread.",
    "start": 24.36,
    "duration": 3.72,
    "file": "narration/thread.mp3"
  },
  {
    "id": "sea",
    "speaker": "narrator",
    "text": "The sea did everything it could… to make him stop.",
    "start": 30.68,
    "duration": 3.912,
    "file": "narration/sea.mp3"
  },
  {
    "id": "lotus",
    "speaker": "narrator",
    "text": "The lotus-eaters offered him forgetting. He accepted.",
    "start": 36.792,
    "duration": 4.992,
    "file": "narration/lotus.mp3"
  },
  {
    "id": "cave",
    "speaker": "narrator",
    "text": "In the giant's cave there was no signal. He wrote one line, and it waited for the sun.",
    "start": 43.984,
    "duration": 6.864,
    "file": "narration/cave.mp3"
  },
  {
    "id": "circe",
    "speaker": "narrator",
    "text": "The enchantress asked permission. He gave it without putting down his cup.",
    "start": 52.848,
    "duration": 5.88,
    "file": "narration/circe.mp3"
  },
  {
    "id": "sirens",
    "speaker": "narrator",
    "text": "The sirens sang the oldest song of all.",
    "start": 60.728,
    "duration": 3.6,
    "file": "narration/sirens.mp3"
  },
  {
    "id": "muted",
    "speaker": "narrator",
    "text": "He had muted them.",
    "start": 67.328,
    "duration": 2.16,
    "file": "narration/muted.mp3"
  },
  {
    "id": "shapes",
    "speaker": "narrator",
    "text": "The shape-shifter wore four faces. It was always the same session.",
    "start": 71.688,
    "duration": 6.072,
    "file": "narration/shapes.mp3"
  },
  {
    "id": "dragon",
    "speaker": "narrator",
    "text": "Then came the dragon of the storm…",
    "start": 80.36,
    "duration": 2.976,
    "file": "narration/dragon.mp3"
  },
  {
    "id": "broke",
    "speaker": "narrator",
    "text": "…and the thread broke.",
    "start": 85.136,
    "duration": 2.232,
    "file": "narration/broke.mp3"
  },
  {
    "id": "switch",
    "speaker": "narrator",
    "text": "At home, his son reached for the switch.",
    "start": 90.768,
    "duration": 3.648,
    "file": "narration/switch.mp3"
  },
  {
    "id": "wait",
    "speaker": "penelope",
    "text": "Wait.",
    "start": 94.916,
    "duration": 2.088,
    "file": "narration/wait.mp3"
  },
  {
    "id": "remembered",
    "speaker": "narrator",
    "text": "But the thread remembered everything.",
    "start": 98.204,
    "duration": 2.808,
    "file": "narration/remembered.mp3"
  },
  {
    "id": "arrow",
    "speaker": "narrator",
    "text": "The king came home a beggar. In his own hall, he loosed a single arrow…",
    "start": 103.412,
    "duration": 6.336,
    "file": "narration/arrow.mp3"
  },
  {
    "id": "rings",
    "speaker": "narrator",
    "text": "…through twelve rings. Twelve works. All done.",
    "start": 111.748,
    "duration": 6.072,
    "file": "narration/rings.mp3"
  },
  {
    "id": "word",
    "speaker": "narrator",
    "text": "From the edge of the world, he sent one word home.",
    "start": 120.42,
    "duration": 4.056,
    "file": "narration/word.mp3"
  },
  {
    "id": "goes-on",
    "speaker": "narrator",
    "text": "The work goes on.",
    "start": 128.676,
    "duration": 2.136,
    "file": "narration/goes-on.mp3"
  },
  {
    "id": "so-can-you",
    "speaker": "narrator",
    "text": "So can you.",
    "start": 131.712,
    "duration": 2.088,
    "file": "narration/so-can-you.mp3"
  }
];
