#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from client_core_boundary_patterns import (
    CLIENT_APP_OWNERSHIP_PATTERNS,
    CLIENT_CORE_SOURCE_PATTERNS,
    CLIENT_RUNTIME_PATTERNS,
    FORBIDDEN_DEPENDENCIES,
    GAME_SURFACE_FORBIDDEN_PATTERNS,
    SCAN_SUFFIXES,
    SKIPPED_COMPONENTS,
    STRICT_RUNTIME_PATTERNS,
    scan_text as scan_text_for_patterns,
)
from client_core_proto_guard import proto_payload_findings as proto_guard_findings

ROOT_DIR = Path(__file__).resolve().parents[1]
SELF_TEST_SCRIPT = ROOT_DIR / "scripts" / "client_core_boundary_selftest.py"
CLIENT_CORE_MANIFEST = ROOT_DIR / "crates" / "looper-client-core" / "Cargo.toml"
CLIENT_CORE_ROOT = Path("crates/looper-client-core")
RUNTIME_ROOTS = ("crates", "ios", "macos", "swift")
CLIENT_RUNTIME_ROOTS = ("ios", "macos", "swift")
RETIRED_RUNTIME_ROOTS = (Path("swift/LooperRealtime"),)
GENERATED_SOURCE_ROOTS = (
    Path("swift/LooperClientCore/Sources/LooperClientCore/Generated"),
)
GENERATED_TEXT_PROVENANCE = {
    ".swift": "This file was autogenerated",
    ".h": "This file was autogenerated",
    ".modulemap": "This file was autogenerated",
}
REALTIME_FORBIDDEN_UI_ROOTS = (
    Path("ios/LooperCompanion/UI/Pinball"),
    Path("ios/LooperCompanion/UI/Maze"),
    Path("ios/LooperCompanion/Support/PinballSettingsKeys.swift"),
    Path("ios/LooperCompanion/Assets.xcassets/PinballBall.imageset"),
    Path("ios/LooperCompanion/Assets.xcassets/MazeBall.imageset"),
)
CONTROL_PLANE_PROTO = Path("crates/agent-control-plane/proto/looper/v1/control_plane.proto")
FRAME_LIMITS_SOURCE = Path("crates/agent-control-plane/src/grpc/frame_limits.rs")
RAW_CLIENT_CORE_BOUNDARY_FILES = (
    CLIENT_CORE_ROOT / "src" / "client.rs",
    CLIENT_CORE_ROOT / "src" / "local_store.rs",
)
FRAME_LIMIT_REQUIRED_MARKERS = (
    "SESSION_CONTROL_FRAME_MAX_BYTES",
    "ensure_client_frame_size",
    "ensure_server_frame_size",
    "resource_exhausted",
    "data-plane fetch",
)


@dataclass(frozen=True)
class Finding:
    path: Path
    line: int
    rule: str
    text: str


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Guard Looper client-core dependency direction and rewrite-only transport boundaries."
    )
    parser.add_argument(
        "--strict-runtime",
        action="store_true",
        help="Also fail on repo-wide no-event-stream/no-unary runtime surfaces after E/F/G integration.",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run synthetic guardrail fixtures and exit without scanning the working tree.",
    )
    args = parser.parse_args()

    if args.self_test:
        return run_self_test_script()

    findings: list[Finding] = []
    findings.extend(check_client_core_dependencies())
    findings.extend(check_raw_client_core_uniffi_exports())
    findings.extend(
        scan_files(
            roots=(CLIENT_CORE_ROOT,),
            patterns=CLIENT_CORE_SOURCE_PATTERNS,
        )
    )

    if args.strict_runtime:
        findings.extend(check_generated_text_provenance())
        findings.extend(check_game_surfaces_do_not_own_realtime())
        findings.extend(check_session_control_frame_contract())
        findings.extend(check_retired_runtime_roots())
        findings.extend(
            scan_files(
                roots=tuple(Path(root) for root in RUNTIME_ROOTS),
                patterns=STRICT_RUNTIME_PATTERNS,
                include_markdown=False,
            )
        )
        findings.extend(
            scan_files(
                roots=tuple(Path(root) for root in CLIENT_RUNTIME_ROOTS),
                patterns=CLIENT_RUNTIME_PATTERNS,
                include_markdown=False,
            )
        )
        findings.extend(
            scan_files(
                roots=(Path("ios/LooperCompanion"), Path("macos/LooperMenuBar")),
                patterns=CLIENT_APP_OWNERSHIP_PATTERNS,
                include_markdown=False,
            )
        )

    if findings:
        print("client-core boundary check failed:")
        for finding in findings:
            print(f"{finding.path}:{finding.line}: {finding.rule}: {finding.text}")
        return 1

    mode = "strict runtime + client-core" if args.strict_runtime else "client-core"
    print(f"client-core boundary check passed ({mode})")
    return 0


def check_client_core_dependencies() -> list[Finding]:
    if not CLIENT_CORE_MANIFEST.exists():
        return [
            Finding(
                path=CLIENT_CORE_MANIFEST.relative_to(ROOT_DIR),
                line=1,
                rule="missing client-core manifest",
                text="expected crates/looper-client-core/Cargo.toml",
            )
        ]

    metadata = cargo_metadata()
    root_id = metadata["resolve"]["root"]
    packages = {package["id"]: package for package in metadata["packages"]}
    root_package = packages[root_id]
    findings: list[Finding] = []

    for dependency in root_package["dependencies"]:
        dependency_name = dependency["name"]
        if dependency_name in FORBIDDEN_DEPENDENCIES:
            findings.append(
                Finding(
                    path=CLIENT_CORE_MANIFEST.relative_to(ROOT_DIR),
                    line=1,
                    rule="forbidden client-core dependency",
                    text=f"{dependency_name} must not be an inward client-core dependency",
                )
            )

    targets = root_package.get("targets", [])
    lib_targets = [target for target in targets if "lib" in target.get("kind", [])]
    if not lib_targets:
        findings.append(
            Finding(
                path=CLIENT_CORE_MANIFEST.relative_to(ROOT_DIR),
                line=1,
                rule="missing library target",
                text="client core must expose a Rust library",
            )
        )
        return findings

    crate_types = set(lib_targets[0].get("crate_types", []))
    required_crate_types = {"lib", "staticlib", "cdylib"}
    missing_crate_types = sorted(required_crate_types - crate_types)
    if missing_crate_types:
        findings.append(
            Finding(
                path=CLIENT_CORE_MANIFEST.relative_to(ROOT_DIR),
                line=1,
                rule="missing UniFFI crate type",
                text=f"missing crate types: {', '.join(missing_crate_types)}",
            )
        )

    return findings


def check_raw_client_core_uniffi_exports() -> list[Finding]:
    findings: list[Finding] = []
    forbidden_markers = ("uniffi::Object", "#[uniffi::export]", "#[uniffi::constructor]")
    for path in RAW_CLIENT_CORE_BOUNDARY_FILES:
        absolute_path = ROOT_DIR / path
        if not absolute_path.exists():
            findings.append(
                Finding(
                    path=path,
                    line=1,
                    rule="missing raw client-core boundary file",
                    text=f"expected {path}",
                )
            )
            continue

        text = absolute_path.read_text(encoding="utf-8", errors="replace")
        for line_number, line in enumerate(text.splitlines(), start=1):
            if any(marker in line for marker in forbidden_markers):
                findings.append(
                    Finding(
                        path=path,
                        line=line_number,
                        rule="raw client-core UniFFI export",
                        text=(
                            "raw client/store types must stay Rust-internal; "
                            "export only LooperClientCoreSessionRuntime"
                        ),
                    )
                )
    return findings


def check_retired_runtime_roots() -> list[Finding]:
    findings: list[Finding] = []
    for path in tracked_source_files(RETIRED_RUNTIME_ROOTS):
        findings.append(
            Finding(
                path=path.relative_to(ROOT_DIR),
                line=1,
                rule="retired runtime root",
                text="swift/LooperRealtime has been retired; use swift/LooperClientCore",
            )
        )
    return findings


def check_generated_text_provenance() -> list[Finding]:
    findings: list[Finding] = []
    for path in tracked_source_files(GENERATED_SOURCE_ROOTS):
        marker = GENERATED_TEXT_PROVENANCE.get(path.suffix)
        if marker is None:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if marker not in text[:512]:
            findings.append(
                Finding(
                    path=path.relative_to(ROOT_DIR),
                    line=1,
                    rule="generated provenance missing",
                    text=f"missing generated-file marker: {marker}",
                )
            )
    return findings


def check_game_surfaces_do_not_own_realtime() -> list[Finding]:
    return scan_files(
        roots=REALTIME_FORBIDDEN_UI_ROOTS,
        patterns=GAME_SURFACE_FORBIDDEN_PATTERNS,
        include_markdown=False,
    )


def check_session_control_frame_contract() -> list[Finding]:
    findings: list[Finding] = []
    findings.extend(check_required_frame_limit_markers())

    absolute_path = ROOT_DIR / CONTROL_PLANE_PROTO
    if not absolute_path.exists():
        return [
            Finding(
                path=CONTROL_PLANE_PROTO,
                line=1,
                rule="missing Session proto",
                text="expected control_plane.proto with Session control-frame definitions",
            )
        ]

    findings.extend(
        Finding(
            path=finding.path,
            line=finding.line,
            rule=finding.rule,
            text=finding.text,
        )
        for finding in proto_guard_findings(
            absolute_path,
            ROOT_DIR / FRAME_LIMITS_SOURCE,
            ROOT_DIR,
        )
    )
    return findings


def run_self_test_script() -> int:
    completed = subprocess.run(
        [sys.executable, str(SELF_TEST_SCRIPT)],
        cwd=ROOT_DIR,
        check=False,
    )
    return completed.returncode


def scan_text(
    path: Path,
    text: str,
    patterns: tuple[tuple[str, re.Pattern[str]], ...],
) -> list[Finding]:
    return scan_text_for_patterns(Finding, path, text, patterns)


def check_required_frame_limit_markers() -> list[Finding]:
    absolute_path = ROOT_DIR / FRAME_LIMITS_SOURCE
    if not absolute_path.exists():
        return [
            Finding(
                path=FRAME_LIMITS_SOURCE,
                line=1,
                rule="missing Session frame limits",
                text="expected grpc/frame_limits.rs to cap Session control frames",
            )
        ]

    text = absolute_path.read_text(encoding="utf-8", errors="replace")
    findings: list[Finding] = []
    for marker in FRAME_LIMIT_REQUIRED_MARKERS:
        if marker not in text:
            findings.append(
                Finding(
                    path=FRAME_LIMITS_SOURCE,
                    line=1,
                    rule="missing Session frame-limit guard",
                    text=f"missing marker: {marker}",
                )
            )
    return findings


def cargo_metadata() -> dict:
    command = [
        "cargo",
        "metadata",
        "--format-version=1",
        "--manifest-path",
        str(CLIENT_CORE_MANIFEST),
    ]
    completed = subprocess.run(
        command,
        cwd=ROOT_DIR,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return json.loads(completed.stdout)


def scan_files(
    roots: tuple[Path, ...],
    patterns: tuple[tuple[str, re.Pattern[str]], ...],
    include_markdown: bool = True,
) -> list[Finding]:
    findings: list[Finding] = []
    for path in tracked_source_files(roots):
        if not include_markdown and path.suffix == ".md":
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        relative_path = path.relative_to(ROOT_DIR)
        findings.extend(scan_text(relative_path, text, patterns))
    return findings


def tracked_source_files(roots: tuple[Path, ...]) -> list[Path]:
    command = ["git", "ls-files", "--cached", "--others", "--exclude-standard", "--"]
    command.extend(str(root) for root in roots)
    completed = subprocess.run(
        command,
        cwd=ROOT_DIR,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    files: list[Path] = []
    for line in completed.stdout.splitlines():
        path = ROOT_DIR / line
        if path.suffix not in SCAN_SUFFIXES or not path.is_file():
            continue
        if SKIPPED_COMPONENTS.intersection(path.relative_to(ROOT_DIR).parts):
            continue
        files.append(path)
    return files


if __name__ == "__main__":
    sys.exit(main())
